version: 2
updates:
  # Enable version updates for Python pip
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "deps(pip)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    # Allow up to 10 open PRs for pip dependencies
    open-pull-requests-limit: 10
    # Reviewers for dependency updates
    reviewers:
      - "tommyod"
    cooldown:
      default-days: 5
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
    

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tommyod"
